version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18
      - npm install --omit=dev
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'
