version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
  pre_build:
    commands:
      - echo "VITE_ENDPOINT_URL=https://app.${DOMAIN_NAME}/apigw/" > .env
      - cat .env
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'
